
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-spark-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kuchiera/Audience2.0.git'
    path: k8smanifests/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: au03-sales-test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
