apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-conf
  namespace: tenant1
data:
  spark-defaults.conf: |
    spark.kubernetes.container.image=eragani/spark:3.3.1

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-spark-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kuchiera/Audience2.0.git'
    path: k8smanifests/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tenant1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
