apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-conf
  namespace: tenant1
data:
  spark-defaults.conf: |
    spark.kubernetes.container.image=eragani/spark:3.3.1

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: tenant1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJlcmFnYW5pIiwicGFzc3dvcmQiOiJBbnVyYWRoYUAxMjM0IyQiLCJlbWFpbCI6ImVyYWdhbmlAZ21haWwuY29tIiwiYXV0aCI6IlpYSmhaMkZ1YVRwQmJuVnlZV1JvWVVBeE1qTTBJeVE9In19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: tenant1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tenant1
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: tenant1
subjects:
- kind: ServiceAccount
  name: spark
  namespace: tenant1
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: my-spark-app-tenant1
  namespace: tenant1
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  template:
    type: Scala
    mode: cluster
    image: "eragani/spark:3.3.1"
    mainClass: "step1.UserCDCEventProcessor"
    mainApplicationFile: "local:///opt/suite/audience2.0/Audience-assembly-0.1.0.jar"
    sparkVersion: "3.3.1"
    restartPolicy:
      type: Never
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
      labels:
        version: 3.3.1
      serviceAccount: spark
    executor:
      cores: 1
      instances: 5
      memory: "512m"
      labels:
        version: 3.3.1
    sparkConf:
      "spark.kubernetes.namespace": "tenant1"
      "spark.kubernetes.authenticate.driver.serviceAccountName": "spark"
      "spark.kubernetes.container.image": "eragani/spark:3.3.1"
      "spark.kubernetes.driver.container.image": "eragani/spark:3.3.1"
      "spark.kubernetes.executor.container.image": "eragani/spark:3.3.1"
      "spark.eventLog.enabled": "false"
      "spark.kubernetes.container.image.pullSecrets": "docker-secret"
    # arguments:
    #   - "au03_sales_test"
