apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: my-spark-app-tenant1
  namespace: tenant1
spec:
  type: Scala
  mode: cluster
  image: "eragani/spark:3.3.1"
  imagePullPolicy: Always
  mainClass: step1.UserCDCEventProcessor
  mainApplicationFile: "local:///opt/suite/audience2.0/Audience-assembly-0.1.0.jar"
  arguments:
    - "au03_sales_test"
  sparkConf:
    "spark.executor.instances": "5"
    "spark.kubernetes.namespace": "tenant1"
    "spark.kubernetes.authenticate.driver.serviceAccountName": "spark"
    "spark.kubernetes.driver.container.image": "eragani/spark:3.3.1"
    "spark.kubernetes.executor.container.image": "eragani/spark:3.3.1"
    "spark.eventLog.enabled": "false"
  imagePullSecrets:
    - docker-secret
