apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  #namespace: tenant1
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "watch", "list", "create", "delete"]
