apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-refresh-job
  namespace: tenant1
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: spark
          containers:
          - name: spark-submit
            image: eragani/spark:3.3.1
            command: ["/bin/bash", "-c"]
            args:
              - >
                spark-submit
                --master k8s://https://192.168.22.235:6443
                --deploy-mode cluster
                --name my-spark-app-tenant1
                --class step1.UserCDCEventProcessor
                --conf spark.executor.instances=5
                --conf spark.kubernetes.namespace=tenant1
                --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark
                --conf spark.kubernetes.container.image=eragani/spark:3.3.1
                --conf spark.kubernetes.driver.container.image=eragani/spark:3.3.1
                --conf spark.kubernetes.executor.container.image=eragani/spark:3.3.1
                --conf spark.eventLog.enabled=false
                --conf spark.kubernetes.container.image.pullSecrets=docker-secret
                local:///opt/suite/audience2.0/Audience-assembly-0.1.0.jar
                au03_sales_test
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "1Gi"
                cpu: "1"
